see see
ruibaby/pinghsu-halo pull request #17
Opened 2023-09-06 07:58 UTC by GodlessLiu

## 目前支持的模版
 - index.html
 - categories.html 
 - category.html
 - tags.html
 - tag.html
 - links.html
 - archives.html
 - post.html
 - 404.html

2023-09-08 02:38 UTC, ruibaby requested changes

2023-09-08 02:38 UTC, ruibaby commented on LICENSE
建议替换为原主题的 LICENSE 文件：https://github.com/chakhsu/pinghsu/blob/master/LICENSE.md

2023-09-08 02:38 UTC, ruibaby commented on screenshot.png
保留。

2023-09-08 02:38 UTC, ruibaby commented on theme.yaml
> +    website: "https://halo.run"
保持原来的配置。

2023-09-08 02:38 UTC, ruibaby commented on theme.yaml
> +  repo: "https://github.com/halo-sigs/theme-starter"
Repo 设置不正确。

2023-09-08 02:38 UTC, ruibaby commented on theme.yaml
> +  version: "1.0"
```suggestion
  version: "2.0.0"
```

2023-09-08 02:38 UTC, ruibaby commented on theme.yaml
> +  require: ">2.0"
```suggestion
  require: ">=2.0.0"
```

2023-09-08 02:38 UTC, ruibaby commented on theme.yaml
> +  displayName: Theme Pinghsu@next
```suggestion
  displayName: Pinghsu
```

2023-09-08 02:38 UTC, ruibaby commented on templates/modules/layout.html
> +    <script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.17.1/build/highlight.min.js"></script>
建议下载到 assets 目录，目前 jsdelivr 在部分地区访问有问题。

此外，highlight.js 是否可以不引入？直接推荐使用者用：https://halo.run/store/apps/app-sqpgf

2023-09-08 02:38 UTC, ruibaby commented on templates/modules/footer.html
> +      src="https://cdn.jsdelivr.net/npm/fastclick@1.0.6/lib/fastclick.min.js"
建议下载到 assets 目录，目前 jsdelivr 在部分地区访问有问题。

2023-09-08 03:04 UTC, GodlessLiu commented
logo 还需要设置一下

2023-09-08 09:00 UTC, ruibaby reviewed
/lgtm

2023-09-08 12:58 UTC, guqing reviewed
/approve

2023-09-08 13:13 UTC, merged

2023-09-11 03:49 UTC, youngledo commented
没有合并到master分支吗，代码不一样啊

2023-09-11 03:53 UTC, ruibaby commented
> 没有合并到master分支吗，代码不一样啊

https://github.com/halo-dev/halo-theme-pinghsu/tree/next

2.0 暂时放在了 next 分支。